name: Build APK Ipank
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Rakit APK Paksa
        run: gradle assembleDebug
      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: Ipank-Loader-Sultan
          path: app/build/outputs/apk/debug/app-debug.apk
          
