name: Build APK Ipank Hardcore
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Jebol Lisensi & Rakit
        run: |
          # Ambil alat rakit versi stabil
          gradle wrapper --gradle-version 6.7.1
          chmod +x gradlew
          # Terima semua lisensi Google secara paksa
          yes | sdkmanager --licenses || true
          # Rakit APK sekarang juga!
          ./gradlew assembleDebug --stacktrace

      - name: Ambil Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Ipank-Loader-Sultan
          path: "**/*.apk"
          
