name: Build APK Ipank
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cari dan Rakit APK Paksa
        run: |
          # Cari dimana file gradle berada dan hajar rakit!
          gradle assembleDebug --stacktrace
      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: Ipank-Loader-Sultan
          path: "**/*.apk"
          
